server:
  port: 8080
  forward-headers-strategy: native
  servlet:
    context-path: /backend
    session:
      cookie:
        path: /

app-version: '@version@'

spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    # 1. Master DB (기존과 동일)
    master:
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        pool-name: Master-HikariCP
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000

    # 2. Slave DB (환경변수로 변경함)
    slave:
      jdbc-url: ${SLAVE_DB_URL}
      username: ${SLAVE_DB_USERNAME}
      password: ${SLAVE_DB_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        pool-name: Slave-HikariCP
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000

  #  profiles:
  #    active: dev
  elasticsearch:
    uris: http://34.64.251.211:9200
    username: elastic
    password: bnk1234!


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  data:
    redis:
      host: 34.64.251.211
      port: 6379


flobank:
  ap:
    host: 34.64.251.211
    port: 9090
  aes:
    secret: ${AES_SECRET}


jwt:
  secret: ${JWT_SECRET}

eximbank:
  api:
    base-url: "https://oapi.koreaexim.go.kr/site/program/financial/exchangeJSON"
    auth-key: "LNyeb6x2OFLu289XSY1tokxFueROPpxI"

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: "https://api.openai.com/v1"

solapi:
  apiKey: ${SOLAPI_API_KEY}
  apiSecret: ${SOLAPI_API_SECRET}
  phoneNumber: ${SOLAPI_PHONE}

terms:
  base-dir: C:/Users/GGG/Desktop/workspace

pinecone:
  api-key: ${PINECONE_API_KEY}
  index-host: https://bank-db-46fp8tb.svc.aped-4627-b74a.pinecone.io
  index-name: bank-db

file:
  upload:
    pdf-ai-path: /app/uploads/pdf_ai
    pdf-products-path: /app/uploads/pdf_products
    pdf-terms-path: /app/uploads/terms

deepl:
  api:
    key: ${DEEPL_API_KEY}

ai-server:
  url: http://34.64.84.82:8000

ai-server-qna:
  url: http://34.64.84.82:8000/api/qna/auto_process

#firebase:
# service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:}


logging:
  level:
    kr.co.api.backend.mapper.DepositMapper: DEBUG
    org.mybatis: DEBUG
